name: Create Project Card on Issue Assign

on:
  issues:
    types: [assigned]

jobs:
  create_project_card:
    runs-on: ubuntu-latest
    steps:
      - name: Create a card in GitHub Project
        env:
          GITHUB_TOKEN: ${{ secrets.KANBAN_WORKFLOW }}
        run: |
          PROJECT_ID="PVT_kwHOAQCcYM4Ao1At"
          ISSUE_ID=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            | jq -r '.node_id')
          
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.github.v4.idl" \
            -d '{"query":"mutation { addProjectV2ItemById(input: {projectId: \"'"$PROJECT_ID"'\", contentId: \"'"$ISSUE_ID"'\") { item { id }}}"}' \
            https://api.github.com/graphql
